<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>train_game</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  	<!-- Include models in the thingy -->
	<ItemGroup>
		<EmbeddedResource Include="./assets/**/*"></EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="Raylib-cs" Version="7.0.1" />
	</ItemGroup>

</Project>
